### ISSUE TITLE
[Feature Request] API for Total Odd/Even

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#1]
### Diễn giải: 
API trả về kết quả là danh sách thống kê chẵn/lẻ cho 12 tháng của tất cả các năm (định dạng tương tự cho API của thống kê chẵn/lẻ ở khoá `odd_by_month`).

### Ví dụ:
```
[
  [
    1,
    "total",
    0,
    1,
    1,
    5,
    2,
    1,
    2
  ],
...
  [
    12,
    "total",
    0,
    0,
    3,
    5,
    4,
    2,
    0
  ]
]
```

**Comment by foremptyonly** [comment]
/v1/645/statistic/oddeven/month
