### ISSUE TITLE
Fix Hot Cold API

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#10]
`/v1/645/statistic/HotCold`
### Diễn giải
Trả về danh sách số lần xuất hiện của banh dựa trên các kỳ ngắn hạn, trung hạn và dài hạn tính từ kỳ mới nhất trở về trước.
* Ngắn hạn (s): đếm số lần xuất hiện của 45 banh dựa trên 10 kỳ quay tính từ kỳ mới nhất
* Trung hạn (m): đếm số lần xuất hiện của 45 banh dựa trên 20 kỳ quay tính từ kỳ mới nhất
* Dài hạn (l): đếm số lần xuất hiện của 45 banh dựa trên 40 kỳ quay tính từ kỳ mới nhất

**Comment by foremptyonly** [comment]
http://13.250.98.221/v1/645/statistic/HotCold

**Comment by kn7007** [comment]
Hot Cold này anh trả về danh sách đếm đủ 45 banh dùm em, nghĩa là từ 1-45, cái nào không xuất hiện thì sẽ là 0

**Comment by foremptyonly** [comment]
Đã fix
