### ISSUE TITLE
[Feature Request] API for Count Ball per period

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#11]
### Diễn giải
Dựa trên #7 . Thêm bộ đếm số lần xuất hiện của 45 banh theo từng kỳ dựa trên kết quả đã lọc.
### Input
Ngày bắt đầu và ngày kết thúc
### Output
Danh sách bao gồm kỳ, ngày và danh sách số lần xuất hiện của 45 banh của từng kỳ đó. Ví dụ kỳ 110 có kết quả là 03 | 05 | 07 | 12 | 27 | 33. Tương ứng với giá trị 3 xuất hiện 1 lần, giá trị 5 xuất hiện 1 lần, giá trị 7 xuất hiện 1 lần, 12 là 1 lần, 27 là 1 lần và 33 là 1 lần. Tương ứng:
```
[
{"id":1,"date":"2016-07-20T00:00:00","ns":[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,...,0]}
...
]
```
`ns` chứa danh sách từng vị trí với số lần xuất hiện tương ứng với giá trị banh (từ 1 đến 45). Giá trị nào xuất hiện 1 lần thì tại vị trí đó trong danh sách `ns` sẽ là 1, 2 lần thì sẽ là 2,...

**Comment by foremptyonly** [comment]
Cái này cho cái chart hay table nào vậy?

**Comment by kn7007** [comment]
Cái này là của Ball Pattern: http://13.250.98.221:8080/Mega645_BallPattern.aspx

**Comment by kn7007** [comment]
> /v1/645/statistic/list/2016-01-01/2018-01-01/nummark

API này hình như cũng chưa hoạt động. Em gắn thành `http://13.250.98.221/v1/645/statistic/list/2016-01-01/2018-01-01/nummark` nó cũng báo 404. Anh kiểm tra lại giúp em.

**Comment by foremptyonly** [comment]
Fix
