### ISSUE TITLE
[feature request] API truy xuất kết quả theo tỷ lệ trên bảng chẵn/ lẻ.

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#12]
**Input:**
Từ ngày - Đến ngày

**Output:**
 Khi click vào kết quả của từng tỷ lệ Chẵn/ Lẻ (vd : 2/4 , 3/3....) hệ thống trả về kết quả vé tương ứng theo số lần và tỷ lệ.

Vd: Tỷ lệ 4/2 trong tháng 1 xuất hiện 3 lần. Khi click vào hệ thống trả về kết quả 3 lần quay trong tháng 1 với tỷ lệ chẵn/ lẻ là 4/2

![1](https://user-images.githubusercontent.com/42494579/44823955-a694b900-abf2-11e8-8491-6abd3cd4182b.png)

**Comment by kn7007** [comment]
Cập nhật
### Input
Tỉ lệ (rate): 0-6, 1-5, 2-4, 3-3, 4-2, 5-1, 6-0
Tháng (month): từ 1 tới 12
Năm (year): 2016, 2017, 2018,... hoặc `total` 
### Output:
Tương tự: `http://13.250.98.221/v1/645/statistic/ball/11`

**Comment by foremptyonly** [comment]
http://13.250.98.221/v1/645/statistic/oddeven/month
http://13.250.98.221/v1/645/statistic/oddeven/month/11
http://13.250.98.221/v1/645/statistic/oddeven/list/odd/5/month/11/
http://13.250.98.221/v1/645/statistic/oddeven/list/odd/5/month/11/year/2017

**Comment by xilliilliix** [comment]
Done
