### ISSUE TITLE
[feature request] API truy xuất kết quả theo tỷ lệ trên bảng Cao/Thấp.

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#13]
**Input:**
Từ ngày - Đến ngày

**Output:**
Khi click vào kết quả của từng tỷ lệ Cao/ THấp (vd : 2/4 , 3/3....) hệ thống trả về kết quả vé tương ứng theo số lần và tỷ lệ.

Vd: Tỷ lệ 4/2 trong tháng 1 xuất hiện 3 lần. Khi click vào hệ thống trả về kết quả 3 lần quay trong tháng 1 với tỷ lệ Cao/Thấp là 4/2

![2](https://user-images.githubusercontent.com/42494579/44824041-0be8aa00-abf3-11e8-8d1d-8be32367137c.png)

**Comment by kn7007** [comment]
Input & Output tương tự #12

**Comment by foremptyonly** [comment]
http://13.250.98.221/v1/645/statistic/LowHigh/month
http://13.250.98.221/v1/645/statistic/LowHigh/month/11
http://13.250.98.221/v1/645/statistic/LowHigh/list/low/3/month/11
http://13.250.98.221/v1/645/statistic/LowHigh/list/low/3/month/11/year/2017

**Comment by xilliilliix** [comment]
Done
