### ISSUE TITLE
Sơ đồ vị trí 645

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#14]
**Input:**
Từ ngày - Đến ngày

**OutPut:**
Dựa trên kết quả mỗi kỳ quay và ngày quay : hệ thống trả ra 06 banh xuất hiện tương ứng vào các cột trên bảng (từ 1-45)

![3](https://user-images.githubusercontent.com/42494579/44824166-b6f96380-abf3-11e8-911e-87f645c08578.png)

**Comment by kn7007** [comment]
Tương tự #11

**Comment by xilliilliix** [comment]
Done
