### ISSUE TITLE
[Ball position] Vị trí banh 645

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#15]
Input:
Yearly 2016, 2017, 2018 and Total 

Output:
Đếm số lần xuất hiện của các banh từ vị trí 1 đến vị trí 6 theo từng năm. ( có tính tỷ trọng của từng số xuất hiện như hình bên dưới) hoặc link http://13.250.98.221:8080/Mega645_BallPosition.aspx

 VD:
![5](https://user-images.githubusercontent.com/42494579/44826008-9e417b80-abfc-11e8-99df-1688f8d80815.png)

**Comment by foremptyonly** [comment]
http://13.250.98.221/v1/645/statistic/ballposition/2016-12-25/2018-3-05

**Comment by kn7007** [comment]
Cần thêm API cho total

**Comment by xilliilliix** [comment]
Total là tất cả các kỳ quay. Total = 2016 + 2017 + 2018... +n

**Comment by foremptyonly** [comment]
http://13.250.98.221/v1/645/statistic/ballposition/2016-12-25/2118-01-01

**Comment by xilliilliix** [comment]
closed! thanks all
