### ISSUE TITLE
[Feature request] Phạm vi giao động TOTAL

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#16]
**Input:**
Total all date

Output:
API tính tổng tất cả các kỳ (2016, 2017, 2018...) của từng vị trí banh (từ vị trí 1 đến vị trí 6)

Vd:
![4](https://user-images.githubusercontent.com/42494579/44824781-f5445200-abf6-11e8-9b75-6b9c058002fd.png)

**Comment by kn7007** [comment]
Bị trùng: #6

**Comment by xilliilliix** [comment]
Done...Thanks ALL!!!
