### ISSUE TITLE
[Keychain 645] Chuỗi khóa

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#17]
Diễn giải:
Dựa vào key đầu các số ra trong kết quả tạo ra Keychain. Vd  02 05 13 18 27 44 => keychain 001124

 **Input:**
Yearly 2016, 2017, 2018.... và Total

**Output:**
Bảng tổng hợp thống kê keychain theo từng tháng và từng năm có tính tổng cộng.

**Feature Popup:**
+ Khi người dùng click vào số lần ra của keychain theo tháng(hoặc tổng cộng keychain) trên bảng. API xuất ra kết quả tương đương của Keychain đó.  
Vd: keychain 001234 tháng 05 ra 2 lần thì popup xuất hiện kết quả "02 04 13 21 35 44" và " 03  05 12 24 36 43"

+ Khi người dùng click vào header tháng đó thì ra cùng kỳ theo tháng của từng năm. Tương tự  chẵn/ lẻ và cao/ thấp. 
Vd: hình đính kèm
![6](https://user-images.githubusercontent.com/42494579/44827441-a8667880-ac02-11e8-83a5-c21b8822770e.png)

**Comment by kn7007** [comment]
Cập nhật
Phần này gồm 3 API
## API thống kê keychain theo năm (có total)
Output tương tự Chẵn/Lẻ hoặc Cao/Thấp

## API thống kê keychain theo tháng dựa trên năm hoặc total
Output trả về kết quả tháng đó của tất cả các năm tương tự #4 hoặc #3 

## API trả về danh sách kết quả dựa theo keychain
Input: keychain, month, year (có `total`).
Output: tương tự #8

**Comment by foremptyonly** [comment]
http://13.250.98.221/v1/645/statistic/Key2Pattern/2016-12-25/2018-3-05
http://13.250.98.221/v1/645/statistic/Key2Pattern/month
http://13.250.98.221/v1/645/statistic/Key2Pattern/month/11
http://13.250.98.221/v1/645/statistic/Key2Pattern/year/2017

**Comment by kn7007** [comment]
Còn thiếu API trả về danh sách kết quả dựa trên key pattern tương tự http://13.250.98.221/v1/645/statistic/oddeven/list/odd/5/month/11/year/2017

**Comment by foremptyonly** [comment]
v1/645/statistic/key2pattern/list/pattern/001123/month/1/year/2017

**Comment by kn7007** [comment]
Thêm trường hợp bỏ year thì lấy danh sách tổng các năm:
/v1/645/statistic/key2pattern/list/pattern/001123/month/1

**Comment by foremptyonly** [comment]
v1/645/statistic/key2pattern/list/pattern/122333/month/1

**Comment by kn7007** [comment]
Thêm dùm em một trường hợp nữa:
Ví dụ v1/645/statistic/key2pattern/list/pattern/122333 là trả về toàn bộ danh sách kết quả của chuỗi khoá tương ứng

**Comment by kn7007** [comment]
Và trường hợp:
Ví dụ v1/645/statistic/key2pattern/list/pattern/122333/year/2017 là trả về toàn bộ danh sách kết quả của chuỗi khoá tương ứng với năm 2017

**Comment by kn7007** [comment]
> v1/645/statistic/key2pattern/list/pattern/122333/month/1

Anh kiểm tra giúp em API này, em gắn vào thành `http://13.250.98.221/v1/645/statistic/key2pattern/list/pattern/122333/month/1` nhưng nó trả về 404

**Comment by xilliilliix** [comment]
Done!!

**Comment by ghostnguyen** [comment]
Có 3 phần:
% current keychain, % today keychain, % growth.

Mỗi link trên mình cần thêm phần nào vậy?

**Comment by foremptyonly** [comment]
Có 3 phần:
% current keychain, % today keychain, % growth.

Mỗi link trên mình cần thêm phần nào vậy?
