### ISSUE TITLE
[Current lapse] Vòng lặp

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#18]
Diễn giải:
+ Cột Current lapse Đếm số lần chưa xuất hiện của từng banh từ 01 đến 45 từ kỳ quay hiện tại. Đối với những banh vừa ra Current lapse luôn luôn bằng 0. Banh 4 có 21 kỳ chưa xuất hiện tính từ kỳ quay hiện tại thì current lapse bằng 21, 26co 9 kỳ chưa xuất hiện thì current lapse bằng 9.
+ Cột tháng 1 đến tháng 12: là đếm số lần xuất hiện các banh theo năm 2016, 2017, 2018 và total 
Vd : hình đính kèm
![7](https://user-images.githubusercontent.com/42494579/44828034-8cb0a180-ac05-11e8-9185-9c951af8284a.png)

**Comment by foremptyonly** [comment]
http://localhost:56813/v1/645/statistic/currentlapse
http://localhost:56813/v1/645/statistic/ballcount/bymonth
http://localhost:56813/v1/645/statistic/ballcount/bymonth/year/2018

**Comment by kn7007** [comment]
Em vẫn chưa hiểu các API này
1. `http://localhost:56813/v1/645/statistic/currentlapse` đang trả về khác với hai API còn lại.

2. `http://localhost:56813/v1/645/statistic/ballcount/bymonth`. API này có phải dùng để lọc theo tháng không? Nếu có thì sẽ truyền tháng vào segment nào trên url.

3. `http://localhost:56813/v1/645/statistic/ballcount/bymonth/year/2018`. Ví dụ kết quả trả về cho giá trị 01 là `[3,2,1,1,0,0,0,1,0,0,0,0,8]`. Với kết quả này hình như 12 giá trị đầu là từ tháng 1-12, giá trị thứ 13 là current lapse?

4. Chưa có API cho Total các năm

**Comment by foremptyonly** [comment]
v1/645/statistic/currentlapse
- Cho cột Ball và cột CurrentLap như trong hình

Update: v1/645/statistic/ballcount/groupbymonth
- Cho các cột còn lại, 12 giá trị = 12 tháng. Giá trị thứ 13 là total.
- Cho tất cả các năm

Update:  /v1/645/statistic/ballcount/groupbymonth/year/2018.
- Như trên nhưng cho năm cụ thể

**Comment by kn7007** [comment]
Nếu vậy anh giúp em gộp kết quả lại thành từng dòng như thế này chẳng hạn
```
[
   [ current_lapse, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, grand_total ]
   45 dòng cho 45 banh.
]
```
Input vào là năm 2016, 2017, 2018, Total tháng từ 1-12 để thống kê theo tháng.
Lúc này em chỉ cần gửi request 1 lần để lấy kết quả đổ dữ liệu chứ không cần 2 lần như trên vì lấy current lapse riêng và giá trị riêng.

**Comment by kn7007** [comment]
Cái trên chắc là Total. Anh thêm giúp em hai cái.
Theo năm: ví dụ v1/645/statistic/CurrentLapseAndCount/year/2016 cho từng năm.
Theo tháng; ví dụ v1/645/statistic/CurrentLapseAndCount/month/1 cho toàn bộ tháng 1 của tất cả các năm.

**Comment by foremptyonly** [comment]
Updated

**Comment by xilliilliix** [comment]
Done....ThankS!!!
