### ISSUE TITLE
[Number Pair 645] Số cặp

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#19]
**Diễn giải:**
Hệ thống thống kê đếm số lần các cặp số thường xuất hiện trong cùng kỳ quay.
Dựa trên kết quả quay số tính ra các cặp (gồm 2 số) xuất hiện trong kỳ quay đó.

 **Input :**
All Date

**Output:**
![1](https://user-images.githubusercontent.com/42494579/45020780-6d5baf00-b01f-11e8-8a14-7aeb78178e7a.png)

Vd: kết quả ngày 20/12/2017 là [2, 4, 12, 17, 24, 33] thì có các cặp số sau:
**[2,4] [2,12] [2,17] [2,24] [2,33] [4,12] [4,17] [4,24] [4,33] [12,17] [12,24] [12,33] [17,24] [17,33] [24,33]**

**Feature Popup**
Cặp [2,4] xuất hiện 5 lần khi click vào số lần (5) xuất hiện thì hệ thống xuất hiện popup kết quả của 5 kỳ có cặp [2,4].

**Comment by foremptyonly** [comment]
v1/645/statistic/pair
v1/645/statistic/pair/list/1/5

**Comment by xilliilliix** [comment]
Thiếu API cho PopUP
**Feature Popup**
Cặp [2,4] xuất hiện 5 lần khi click vào số lần (5) xuất hiện thì hệ thống xuất hiện popup kết quả của 5 kỳ có cặp [2,4].

**Comment by xilliilliix** [comment]
Done, thanks all
