### ISSUE TITLE
[Basic Report 645]

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#21]
**Diễn giải:**
Báo cáo phân tích cơ bản về các đặc tính cơ bản của vé trúng thưởng dựa vào kết quả hàng ngày.

**Input:**
From Date To Date

**OutPut:**
Draw Date (kỳ quay)
Date (ngày)
Vị trí banh gồm : Ball 1, Ball 2, Ball 3, Ball 4, Ball 5, Ball 6

Key Đầu gồm : Ks 1, Ks 2, Ks 3, Ks 4, Ks 5, Ks 6 =>VD: Kết quả 02 04 12 15 22 34 => Keychain 001123 

Key High/Low : với Low từ 0-22 , High từ 23-45. Key Low gán số 1, Key High gán 2. VD: Kết quả 02 04 12 23 35 44 => Key High/Low là 111222 - 3/3 (3 low và 3 high)

Key Even/Odd: với Odd là lẻ banh có số 1, 3, 5, 7 ,9, 11......... Even là chẵn banh có số 2, 4, 6 ,8, 10.....  Key Odd gán số 1, Key Even gán số 2. Vd:  Kết quả 02 04 12 23 35 44 => Key Even/Odd là 222112 - 4/2 (4 even và 2 odd)

![1](https://user-images.githubusercontent.com/42494579/45201023-0d554a80-b263-11e8-9a77-bfc0aab7d9f8.png)

**Comment by foremptyonly** [comment]
v1/645/statistic/basicreport/2016-01-01/2019-01-01

**Comment by xilliilliix** [comment]
Done...Thank!!!
