### ISSUE TITLE
[Feature Request] Ball Count Per Position

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#24]
## Diễn giải
Đếm giá trị banh xuất hiện của từng vị trí banh theo từng năm và `total`

## Input
Là giá trị của năm: 2016, 2017, 2018,... hoặc `total`

## Output
Danh sách giá trị xuất hiện (45 giá trị) của 6 vị trí banh. Ví dụ

```
{
   "bp1": [5 ,12, 11, 3, .... , 0, 0, 0] // Danh sách số lần xuất hiện của từng giá trị tại banh số 1
...
   "bp6": [0, 0, 0, 0, .... , 3, 9, 7] // Danh sách số lần xuất hiện của từng giá trị banh banh số 6
}
```

**Comment by foremptyonly** [comment]
v1/645/statistic/ballcount/groupbymonth
- Cho các cột còn lại, 12 giá trị = 12 tháng. Giá trị thứ 13 là total.
- Cho tất cả các năm

/v1/645/statistic/ballcount/groupbymonth/year/2018.
- Như trên nhưng cho năm cụ thể

**Comment by kn7007** [comment]
Hình như có chút nhầm lần. Cái này là banh ở vị trí thứ 1 tới thứ 6 chứ không phải giá trị của banh từ 1-45. Nhờ anh điều chỉnh lại giúp em

**Comment by foremptyonly** [comment]
http://localhost:56813/v1/645/statistic/positionball
http://localhost:56813/v1/645/statistic/positionball/2016
