### ISSUE TITLE
[Feature Request] Add Month Filter for Result

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#26]
Theo như #7 đã thống kê được kết quả theo ngày: `/v1/645/statistic/list/2016-1-4/2019-1-1`
Cần thêm thống kê kết quả theo tháng. Ví dụ: `/v1/645/statistic/list/month/1` sẽ trả về toàn bộ danh sách kết quả của tháng 1 trong tất cả các năm hiện có.

### Input
Giá trị tháng từ 1-12

### Output
Danh sách kết quả của tháng trong tất cả các năm tương tự output #7

**Comment by foremptyonly** [comment]
v1/645/statistic/list/month/1
