### ISSUE TITLE
[Feature Request] API for Total Low/High per month

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#4]
Tương tự #3 

### Diễn giải: 
API trả về danh sách kết quả thống kết cao/thấp của một tháng chỉ định trong tất cả các năm.

### Input: 
Nhận vào tháng là số đếm đại diện cho tháng hoặc tên của tháng thuộc danh sách `["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"]`. Ví dụ tháng 7 nhận vào là `7` hoặc `jul` (định dạng tương tự cho API của thống kê cao/thấp ở khoá `low_by_month` nhưng với tháng cố định và năm thay đổi).

### Ouput:
```
[
  [
    7,
    2016,
    0,
    1,
    1,
    5,
    2,
    1,
    2
  ],
  [
    7,
    2017,
    0,
    1,
    1,
    5,
    2,
    1,
    2
  ],
  [
    7,
    2018,
    0,
    0,
    3,
    5,
    4,
    2,
    0
  ]
]
```

**Comment by foremptyonly** [comment]
/v1/645/statistic/lowhigh/month/1
