### ISSUE TITLE
Tỷ lệ chẵn/ lẻ - Thống kê chi tiết bị ngược - 645

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#41]
http://52.74.126.166/v1/645/statistic/detailreport/2016-01-01/2099-01-01
 [
        408,
        1,
        "01-03-2019",
        15,
        23,
        29,
        31,
        38,
        43,
        179,
        "122334",
        "1/5",
        "1/5", **<===========**
        "",
        "",
        "15,23",
        "",
        "15",
        ""
    ],
    [
        409,
        2,
        "03-03-2019",
        1,
        13,
        17,
        20,
        30,
        45,
        126,
        "011234",
        "2/4",
        "4/2", **<===========**
        "",
        "20",
        "1,13,45",
        "",
        "30",
        "30"
    ]
![image](https://user-images.githubusercontent.com/42494579/53777614-960c2500-3f2c-11e9-84ea-8ec38322bd60.png)

**Comment by foremptyonly** [comment]
Fix

**Comment by xilliilliix** [comment]
Done, thanks!!!!
