### ISSUE TITLE
Reset 645 ;Max4D lỗi

### ISSUE THREAD

**Issue by xilliilliix** [foremptyonly/a79#42]
http://52.74.126.166/v1/max4d/statistic/reset
http://52.74.126.166/v1/645/statistic/reset
![image](https://user-images.githubusercontent.com/42494579/53847931-24dc7880-3fe5-11e9-9625-6e2a552345c9.png)

**Comment by foremptyonly** [comment]
Fix. Lỗi nhập liệu sai format cho Max4d đợt 330

**Comment by xilliilliix** [comment]
Đã chạy dc, thanks!!!
