### ISSUE TITLE
[Feature Request] API for Ball Count per Ball

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#5]
### Diễn giải:
API nhận vào giá trị banh từ 1-45. Trả về danh sách kết quả có chứa banh tương ứng đó. Ví dụ nhận vào giá trị là 28 thì trả về danh sách toàn bộ các kỳ quay có banh 28 xuất hiện.

### Input:
Một giá trị banh là số nguyên là từ 1 đến 45

### Output
Mảng danh sách kết quả bao gồm kỳ, ngày và giá trị của 6 banh nhưng có banh yêu cầu trong input
```
[
[322, '2018-12-08', [05, 16, 17, 28, 31,38]],
...
[325, '2018-19-08', [16,18,28 ,36 ,37,45]],
]
```

**Comment by foremptyonly** [comment]
http://localhost:56813/v1/645/statistic/ball/11
