### ISSUE TITLE
[Feature Request] API for Total Ball Range per Ball

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#6]
### Diễn giải
Hiện tại đã có API cho Ball Range: v1/645/statistic/BallRange/2016-12-25/2018-3-05/fr nhưng là thống kê theo từng năm. Cần thêm thống kê cho tất cả các năm tương tự Chẳn/Lẻ (#1) và (#2).

### Output
Tương tự v1/645/statistic/BallRange/ từ `body1` tới `body6` nhưng cho total

**Comment by foremptyonly** [comment]
http://localhost:56813/v1/645/statistic/ballrange/fr
