### ISSUE TITLE
[Feature Request] Add Filter for Result

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#7]
### Actual Behavior
Hiện tại API /645.json trả về tất cả kết quả hiện có

### Expected Behavior
Thêm bộ lọc ngày cho API trên. Ví dụ
`/645.json/2016-07-20/2016-08-17` là lọc kết quả từ 20/07/2016 đến 17/08/2016

**Comment by foremptyonly** [comment]
http://localhost:56813/v1/645/statistic/list/2016-1-4/2019-1-1
