### ISSUE TITLE
[Feature Request] API for Total Ball Range per Ball per month

### ISSUE THREAD

**Issue by kn7007** [foremptyonly/a79#9]
### Diễn giải
Tương tự /v1/645/statistic/BallRange nhưng thống kê vị trí banh theo tháng cố định của tất cả các năm (tương tự #3) nhưng là thống kê vị trí banh.
### Input
Nhận vào ví trị banh `1-6` và tháng `1-12`
### Output
Tương tự /v1/645/statistic/BallRange nhưng theo tháng cố định của tất cả năm. Ví dụ tháng 7 và vị trí banh thứ 1
`
[
 [ 7, 2016 , [..] ],
 [ 7, 2017 , [..] ],
 [ 7, 2018 , [..] ]
]
`

**Comment by foremptyonly** [comment]
http://localhost:56813/v1/645/statistic/ballrange/10/2/fr

**Comment by foremptyonly** [comment]
http://13.250.98.221/v1/645/statistic/BallRange/2/6/fr

**Comment by foremptyonly** [comment]
http://13.250.98.221/v1/645/statistic/BallRange/11/6/fr

**Comment by kn7007** [comment]
API này hình như đang có vấn đề:
Ví dụ
Vị trí 1 tháng 1: http://13.250.98.221/v1/645/statistic/BallRange/1/1/fr
Vị trí 1 tháng 9: http://13.250.98.221/v1/645/statistic/BallRange/9/1/fr
đều có kết quả như nhau, thậm chí là giống các tháng còn lại.

Nếu đúng, ví dụ ví trị 1 tháng 1 và banh số 1:
Năm 2016 là 0, 2017 là 2, 2018 là 3 nhưng hiện tại kết quả luôn là
`[1,[5,25,7],37,0.1138461538461538461538461538]`

**Comment by foremptyonly** [comment]
Đã fix
